name: WebApi-Template-CA
on:
  push:
    branches:
      - master
jobs:
  Build:
    runs-on: ubuntu-latest
    environment: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore src/Api/Api.csproj
      - name: Build
        run: dotnet build src/Api/Api.csproj --no-restore
      - name: Upload Build
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: src/Api/bin/Release

  UnitTests:
    needs: [Build]
    runs-on: ubuntu-latest
    environment: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-output
          path: build
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore src/Api/Api.csproj
      - name: Test
        run: dotnet test --filter FullyQualifiedName~UnitTests
